controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    diagnostic_period: 1

    effort_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

effort_controller:
  ros__parameters:
    joints:
      - J0
      - J5
    interface_name: effort

position_trajectory_controller:
  ros__parameters:
    joints:
      - J0
      - J5
    command_interfaces: [position]
    state_interfaces: [position]
